config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'tops#index'

  get 'help', action: :index, controller: 'helps'

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end

  resources :users, only: %i[show edit update]
  resources :teams do
    member do
      patch :owner_change
    end
    collection do
      get :search
    end
    resources :groups, controller: 'teams/groups', only: %i[show create]
    resources :messages, controller: 'teams/messages', only: %i[create destroy]
    resources :tags, controller: 'teams/tags', only: %i[index new create destroy]
    resources :members, controller: 'teams/members', only: %i[show create destroy]
    resources :knowledges, controller: 'teams/knowledges' do
      collection do
        get :search
      end
      resources :tips, controller: 'teams/knowledges/tips' do
        collection do
          get :search
        end
      end
      resources :stocks, controller: 'teams/knowledges/stocks', only: %i[create destroy]
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index; end
end

app/views/tops/index.html.erb
<header class="py-3 bg-image-full">
    <div class="text-center my-4">
        <div>
            <div class="error-box">
                <% if notice %>
                    <span class="alert alert-notice"><%= notice %></span>
                <% end %>
                <% if alert %>
                    <span class="alert alert-error"><%= alert %></span>
                <% end %>
            </div>
            <h1 class="main-title">Reco!</h1>
            <h2 class="main-content">情報を記録・管理・共有できるアプリ</h2>
            <h2 class="main-content">未来のために記録を残しましょう！</h2>
        </div>
    </div>
    <div class="text-center my-5">
        <button class="top-btn"><a href="/users/sign_in"><%= I18n.t('views.messages.sign_in') %></a></button>
        <button class="top-btn"><a href="/users/sign_up"><%= I18n.t('views.messages.sign_up') %></a></button>
        <button class="top-btn guest-btn"><%= link_to I18n.t('views.messages.guest_sign_in'), users_guest_sign_in_path, method: :post %></button>
        <button class="top-btn admin-guest-btn"><%= link_to I18n.t('views.messages.admin_guest_sign_in'), users_admin_guest_sign_in_path, method: :post %></button>
    </div>
</header>

<section class="py-5 container">
    <div class="row justify-content-center">
        <div class="sub-content">
            <h2>日々行った事を、</h2>
            <h2>簡単に記録・管理・共有したい。</h2>
            <hr>
            <p>Reco! はそのお悩みを解消します。</p>
            <p>チームで使用しナレッジを高めましょう！<br>もちろん個人での利用も可能です。</p>
            <p>使用方法によっては、<br>日常のあらゆるシーンで活躍するはずです！</p>
            <p>主な機能を3つ紹介します。</p>
        </div>
    </div>
</section>

<div class="py-2 bg-image-full">
    <div class="container">
        <h2 class="top-function-num text-center text-white">機能①</h2>
            <div class="top-function-explanation text-center justify-content-evenly row">
                <div class="col-12 col-lg-6">
                    <h3 class="text-white">個人・チーム機能</h3>
                    <p class="text-white">簡単にチームを作成する事ができます。</p>
                    <p class="text-white">チームへの招待は、登録されたメールアドレスにより行います。</p>
                </div>
                <div class="col-12 col-lg-6">
                    <%= image_tag 'top1.png', size: '500x350', class: 'rounded img-fluid' %>
                </div>
            </div>
    </div>
</div>

<div class="py-2 my-5 bg-image-full ">
    <div class="container">
        <h2 class="top-function-num text-center text-white">機能②</h2>
        <div class="top-function-explanation text-center justify-content-evenly row">
            <div class="col-12 col-lg-6">
                <h3 class="text-white">メッセージ機能</h3>
                <p class="text-white">1対1から複数人でのやり取りが可能です。</p>
                <p class="text-white">チームに参加した時点で、チームメッセージに参加しているので、</p>
                <p class="text-white">すぐにメッセージでのやり取りが可能です。</p>
            </div>
            <div class="col-12 col-lg-6">
                <%= image_tag 'top2.png', size: '500x350', class: 'rounded img-fluid' %>
            </div>
        </div>
    </div>
</div>

<div class="py-2 my-5 bg-image-full ">
    <div class="container">
        <h2 class="top-function-num text-center text-white">機能③</h2>
        <div class="top-function-explanation text-center justify-content-evenly row">
            <div class="col-12 col-lg-6">
                <h3 class="text-white">ナレッジ・ティップ機能</h3>
                <p class="text-white">ナレッジが親項目、ティップが子項目として機能します。</p>
                <p class="text-white">ティップを蓄積していきましょう。</p>
            </div>
            <div class="col-12 col-lg-6">
                <%= image_tag 'top3.png', size: '500x350', class: 'rounded img-fluid' %>
            </div>
        </div>
    </div>
</div>

<section class="py-5">
    <div class="container my-5">
        <div class="a-single-word">
            <p class="mb-0 text-center">これらの機能を駆使して頂く事により、</p>
            <p class="mb-0 text-center">生活のお役に立てれば光栄です。</p>
        </div>
    </div>
</section>

<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Reco! 2021</p></div>
</footer>

<script>
    ScrollReveal().reveal('.top-function-explanation', {
    duration: 1600,
    scale: 0.1,
});


ScrollReveal().reveal('.main-title', {
    duration: 1600,
    scale: 4,
});
</script>