config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'tops#index'

  get 'help', action: :index, controller: 'helps'

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end

  resources :users, only: %i[show edit update]
  resources :teams do
    member do
      patch :owner_change
    end
    collection do
      get :search
    end
    resources :groups, controller: 'teams/groups', only: %i[show create]
    resources :messages, controller: 'teams/messages', only: %i[create destroy]
    resources :tags, controller: 'teams/tags', only: %i[index new create destroy]
    resources :members, controller: 'teams/members', only: %i[show create destroy]
    resources :knowledges, controller: 'teams/knowledges' do
      collection do
        get :search
      end
      resources :tips, controller: 'teams/knowledges/tips' do
        collection do
          get :search
        end
      end
      resources :stocks, controller: 'teams/knowledges/stocks', only: %i[create destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, length: { in: 1..30 }
  validates :email, presence: true, length: { in: 1..255 }
  validates :introduction, length: { maximum: 200 }

  has_many :teams, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :members_teams, through: :members, source: :team

  mount_uploader :image, ImageUploader

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.username = 'ゲスト'
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@example.com') do |user|
      user.username = 'ゲスト管理者'
      user.password = SecureRandom.urlsafe_base64
      user.admin = 'true'
    end
  end
end

app/controllers/teams/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :same_team_check, only: :show

  def show
    @user = @team.users.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:delete_image]
      @user.image = nil
      @user.save
      render :edit
      nil
    elsif @user.update(user_params)
      redirect_to user_path, notice: '編集しました。'
      bypass_sign_in(@user)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :image, :image_cache, :delete_image,
                                 :introduction, :admin)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(current_user.id), notice: 'ゲストユーザーとしてログインしました。'
  end

  def admin_guest_sign_in
    guest_user = User.admin_guest
    sign_in guest_user
    redirect_to user_path(current_user.id), notice: '管理者ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_check
  before_action :set_user

  def show; end

  def edit; end

  def update
    if params[:delete_image]
      @user.image = nil
      @user.save
      render :edit
    elsif @user.update(user_params)
      redirect_to user_path, notice: '編集しました。'
      bypass_sign_in(@user)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :image, :image_cache, :delete_image,
                                 :introduction, :admin)
  end
end

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation", style="float: right;">
      <h2><%= t("errors.template.header", model: User.model_name.human, count: @user.errors.count) %></h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1 class="app-function-title"><span>User</span>編集</h1>

  <div class="form-user-edit">

      <%= form.label :名前 %>
      <%= form.text_field :username, class: 'form-control', placeholder: '名前を入力して下さい。' %>

      <%= form.label :メールアドレス %>
      <%= form.email_field :email, class: 'form-control', placeholder: 'メールアドレスを入力して下さい。' %>

      <%= image_tag @user.image.url, size: '300x200' if @user.image && @user.image.url %>
      <%= form.hidden_field :image_cache %>

      <div class="image-field row">
        <div class="col-12 col-lg-1">
          <%= form.label :image, '画像', class: 'image-input-btn' %>
        </div>
        <div class="col-12 col-lg-4">
          <%= form.file_field :image, class: 'image-form' %>
        </div>
        <div class="col-12 col-lg-1">
          <%= form.submit value: "設定している画像を削除する。",name: "delete_image",data: { confirm: "画像を削除しますか？"}, class:'btn btn-danger delete-image' %>
        </div>
      </div>

      <%= form.label :introduction, '自己紹介(200字以内)' %>
      <%= form.text_area :introduction, class: 'form-control area-field', placeholder: '自己紹介を入力して下さい。' %>

      <%= form.label :password, 'パスワード(6字以上)' %>
      <%= form.password_field :password, class: 'form-control', placeholder: 'パスワードを入力して下さい。' %>


      <%= form.label :パスワード確認 %>
      <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'パスワードを入力して下さい。' %>

    <div class="action">
      <%= form.submit I18n.t('views.button.register'), class: 'custom-btn new-link' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile row">
  <h1 class="app-function-title col-12"><span>User</span>マイページ</h1>

  <div class="profile-image col-12 col-lg-6">
    <%= image_tag @user.image.url, size: '400x300' if @user.image && @user.image.url %>
  </div>

  <div class="profile-box col-12 col-lg-6">

    <h2 class="profile-name"><%= @user.username %></h2>

    <div class="profile-function">
      <ul>
        <li><%= link_to '個人記録・チーム記録', teams_path, class: 'btn user-show-btn' %></li>
        <li>
          <% if current_user == User.find(params[:id]) %>
            <%= link_to 'ユーザ編集', edit_user_path, class: 'btn user-show-btn' %>
          <% end %>
        </li>
        <li>
          <% if current_user.admin? %>
            <%= link_to '管理者画面', rails_admin_path, class: 'btn user-show-btn' %>
          <% end %>
        </li>
      </ul>
    </div>

    <div class="profile-bio">
      <p><%= @user.introduction %></p>
    </div>

  </div>
</div>