config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'tops#index'

  get 'help', action: :index, controller: 'helps'

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end

  resources :users, only: %i[show edit update]
  resources :teams do
    member do
      patch :owner_change
    end
    collection do
      get :search
    end
    resources :groups, controller: 'teams/groups', only: %i[show create]
    resources :messages, controller: 'teams/messages', only: %i[create destroy]
    resources :tags, controller: 'teams/tags', only: %i[index new create destroy]
    resources :members, controller: 'teams/members', only: %i[show create destroy]
    resources :knowledges, controller: 'teams/knowledges' do
      collection do
        get :search
      end
      resources :tips, controller: 'teams/knowledges/tips' do
        collection do
          get :search
        end
      end
      resources :stocks, controller: 'teams/knowledges/stocks', only: %i[create destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reco!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://unpkg.com/scrollreveal"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <div class="head">
    <% if controller.controller_name == 'tops' || controller.controller_name == 'registrations' || controller.controller_name == 'sessions' || controller.controller_name == 'helps' %>
      <%= render 'shared/layout/header' %>
    <% end %>
    </div>
      <% unless controller.controller_name == 'tops' %>
        <div class="alert-space">
          <% if notice %>
            <p class="alert alert-info"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
        </div>
      <% end %>
  </header>

  <% if controller.controller_name == 'tops' %>
    <%= yield %>
  <% else %>
    <% unless controller.controller_name == 'tops' || controller.controller_name == 'registrations' || controller.controller_name == 'sessions' || controller.controller_name == 'helps' || controller.controller_name == 'passwords' %>
      <div id="sidebar">
        <div class="list">
          <div class="item header-title"></div>
          <div class="item"><i class="fa fa-home"></i>  <%= link_to I18n.t('views.messages.my_page'), user_path(current_user.id) %></div>
          <div class="item"><i class="fa fa-users"></i>  <%= link_to '個人・チーム記録一覧', teams_path %></div>
          <div class="item"><i class="fa fa-question-circle"></i>  <%= link_to 'ヘルプ', help_path %></div>
          <div class="item"><i class="fa fa-power-off"></i>  <%= link_to I18n.t('views.messages.log_out'), destroy_user_session_path, method: :delete %></div>
        </div>
      </div>
      <div id="sidebar-btn" class="toggle-btn side-space" onclick="toggleSidebar(this)">
        <i class="fa fa-forward" id="open-btn">OPEN MENU</i>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  <% end %>

  </body>
</html>